# Generated by Django 6.1 on 2026-08-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning_logs", "0002_entry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="date_add",
            new_name="date_added",
        ),
    ]
